name: Publish Docker image
on:
  workflow_dispatch
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Preparation
        id: prep
        run: |
          REGISTRY="ghcr.io"
          IMAGE="${REGISTRY}/lazarbozic94/${{ github.event.repository.name }}"
          TAGS="${IMAGE}:${{ github.sha }}"
          if [[ $GITHUB_REF == ref/head/master ]]; then
            TAGS="${TAGS},${IMAGE}:latest"
          fi
          echo ::set-output name=tags::${TAGS}
          
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: linux/arm/v7
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
          # registry: docker.pkg.github.com
          # username: ${{ github.repository_owner }}
          # password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to GitHub Packages
        env: 
          version : ${{ github.repository }}/${{ github.event.repository.name }}
        uses: docker/build-push-action@v2
        with:
          platforms: linux/arm/v7
          context: .
          tags: ${{ steps.prep.outputs.tags }}
          push: true
          
